client-origin-url: https://localhost:4200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  application:
    name: vip-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: orders
              uri: lb://java-api
              predicates:
                  - Path=/api/orders
              filters:
                - name: CircuitBreaker
                  args:
                    name: OrdersServiceCircuitBreaker
                    fallbackUri: forward:/fallback

