client-origin-url: ${client-origin-url}

eureka:
  client:
    service-url:
      defaultZone: ${eureka-uri}

spring:
  application:
    name: vip-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: orders
              uri: lb://java-api
              predicates:
                - Path=/api/orders
              filters:
                - name: CircuitBreaker
                  args:
                    name: OrdersServiceCircuitBreaker
                    fallbackUri: forward:/fallback

